### ISSUE TITLE
Is it possible to develop a script where you enter the action name and put the command ID on the clipboard?

### ISSUE THREAD

**Issue by Lo-lo78** [Buy-One/REAPER-scripts#10]
@Buy-One 
Hi, I often find myself looking for the command ID of actions.
To speed up the procedure, it is possible to enter the name of the action in an input field and after entering, insert the ID command into the clipboard.
I know that in reaper-kb.ini there are all the action names and command IDs.
At this point there would also be a second script that does the opposite.
From the command ID find the name of the action.
Do you like the idea?
It would help me. ;)
Thank you!

**Comment by Buy-One** [comment]
Can you clarify what type of script you're looking for: command ID to script name OR script name to command ID?

**Comment by Lo-lo78** [comment]
> Can you clarify what type of script you're looking for: command ID to script name OR script name to command ID?
Hi Buyone, often when you do some operations you need the command ID.
It can happen with cycle actions or when you try to generate a script with AI.
Unfortunately chat gpt can't figure out how to get data from reaper-kb.ini.
Then name and command ID.
👍

**Comment by Buy-One** [comment]
A command ID can be obtained from the Action list. Can't you use the Action list?

**Comment by Lo-lo78** [comment]
Don't laugh! :)
I tried to train the AI ​​and after hours I couldn't get the script to work.
It's probably not possible to do this with Reaper.
The only way is what can already be done from the action list.
This is the broken script:


function GetUserInput()
    local ret, user_input = reaper.GetUserInputs("Inserisci il nome dell'azione", 1, "Nome dell'azione:", "")
    if ret then
        return user_input
    else
        return nil
    end
end

function GetActionID(action_name)
    local reaper_ini_path = reaper.get_ini_file()
    local file = io.open(reaper_ini_path, "r")
    if file then
        for line in file:lines() do
            local cmd_id, cmd_name = line:match("^KEY %d+ %d+ %d+ %d+ %d+ %d+ (%d+) .- : .- : .- : .- : (.+)$")
            if cmd_id then
                local _, cmd_name_from_ini = line:match("^KEY %d+ %d+ %d+ %d+ %d+ %d+ %d+ .- : .- : .- : .- : (.+)$")
                if cmd_name_from_ini and cmd_name_from_ini == action_name then
                    file:close()
                    return tonumber(cmd_id)
                end
            end
        end
        file:close()
    end
    return nil
end

function SetClipboardText(text)
    reaper.CF_SetClipboard(text)
end

function Main()
    local user_input = GetUserInput()
    if user_input then
        local action_id = GetActionID(user_input)
        if action_id then
            SetClipboardText(tostring(action_id))
            reaper.ShowMessageBox("ID dell'azione inserito negli appunti di Windows.", "Successo", 0)
        else
            reaper.ShowMessageBox("Azione non trovata.", "Errore", 0)
        end
    end
end

Main()

**Comment by Buy-One** [comment]
Can you clarify why you need a script if action command IDs can be copied to clipboard directly from the action list, right click the action -> Copy selected action command ID. I assume that such need may stem from your sight problems but i'd like to also understand what prevents you from using the Action list.

**Comment by Lo-lo78** [comment]
I don't have a real problem using the action list.
I was just thinking about generating a script that would make the procedure faster.
I'll explain better:
on OSARA it is possible to instantly know the name of the action linked to a shortcut.
I copy it to the clipboard and open the action list and get the command ID.
Exactly as you say.
I wanted to generate a script with AI that would open an entry field where I could paste the name directly from the clipboard and once you entered you would find the command ID in the clipboard.
It's just to be faster but it's not extremely important.
No it is not a problem related to visibility or accessibility.
It's just a way to speed up the workflow.
But as you say it's already simple with Reaper.
Shall I close the issue?
