### ISSUE TITLE
BuyOne_FX presets menu errors

### ISSUE THREAD

**Issue by romanskorobagatko** [Buy-One/REAPER-scripts#11]
I’m getting this error when executing script with mouse cursor over the track in tcp:

BuyOne_FX presets menu (guide inside).lua:364: bad argument #1 to
'TakeFX_CopyToTrack' (Medialtem_Take expected)

And this one when mouse cursor is over a media item:

BuyOne_FX presets menu (guide inside).lua:365: attempt to sub a 'string' with a
'number'

**Comment by Buy-One** [comment]
Hi

Did it ever work for you or is this your first use? If it did work, since what REAPER build has it stopped working?

**Comment by romanskorobagatko** [comment]
@Buy-One It was a first use, I haven’t tried launching this script before.

**Comment by Buy-One** [comment]
Thank you, will investigate.

**Comment by Buy-One** [comment]
Another question. Are you using files from this repo or from ReaPack?

**Comment by romanskorobagatko** [comment]
@Buy-One ReaPack, Version: 2.0

**Comment by Buy-One** [comment]
My scripts in ReaPack are outdated and unsupported. Please download them from this repository. 

Your bug report prompted me to revise and optimize this script and i'm going to update it soon, but for the time being you still can use the current version, only make sure to avoid REAPER builds 7.09 - 7.20 where it's super glitchy due to bug in ReaScript API.

https://github.com/Buy-One/REAPER-scripts/blob/main/FX/BuyOne_FX%20presets%20menu%20(guide%20inside).lua

**Comment by Buy-One** [comment]
Just updated to version 2.1

**Comment by romanskorobagatko** [comment]
@Buy-One It works but a console window appears.
![image](https://github.com/user-attachments/assets/cd539b39-b39f-4aea-9f4c-d89da25afaac)

**Comment by Buy-One** [comment]
Sorry, removed that,

**Comment by romanskorobagatko** [comment]
@Buy-One Thank you. Should I remove your ReaPack repository and use these scripts from Github?

**Comment by Buy-One** [comment]
My philosophy is "if it ain't broke don't fix it", so as far as i'm concerned scripts from ReaPack which still work can remain in use, but if something bugs out then the script version from this repo would be the first thing to try.

For completely new scripts though this repo is the only address.  I don't submit new scripts to ReaPack.

**Comment by romanskorobagatko** [comment]
@Buy-One Thank you for explanation as well as for the great scripts, I appreciate it!

**Comment by Buy-One** [comment]
Sure. If you consider the issue resolved, feel free to close the thread.
