### ISSUE TITLE
BuyOne_Dynamic ReaperMenu error

### ISSUE THREAD

**Issue by romanskorobagatko** [Buy-One/REAPER-scripts#12]
I’ve got this error when clicking "LOAD REAPER MENU FILE" after I loaded one of my menus: 

BuyOne_Dynamic ReaperMenu (guide inside).lua:246: attempt to index a nil value
(field '?')

So it is impossible to load a different menu now.

**Comment by Buy-One** [comment]
Hi,

Same question. Did it ever work for you or is this your first use? If it did work, since what REAPER build has it stopped working?

**Comment by romanskorobagatko** [comment]
@Buy-One It was a first use, I haven’t tried launching this script before.

**Comment by Buy-One** [comment]
Thank you, will investigate.

**Comment by Buy-One** [comment]
Another question. Are you using files from this repo or from ReaPack? Asking because in the file from this repo line 246 cannot generate an error. If you're using the file from this repo, please attach your version to your reply.

**Comment by romanskorobagatko** [comment]
@Buy-One ReaPack, Version: 1.0

**Comment by Buy-One** [comment]
My scripts in ReaPack are outdated and unsupported. Please download them from this repository.

https://github.com/Buy-One/REAPER-scripts/blob/main/Misc/BuyOne_Dynamic%20ReaperMenu%20(guide%20inside).lua
