### ISSUE TITLE
take envelope

### ISSUE THREAD

**Issue by tohubohu38** [Buy-One/REAPER-scripts#2]
hi,

there is an alert when creating for example the take volume envelope script.

line 144 : "then" expected near "local"

thanks again for these scripts

**Comment by Buy-One** [comment]
Hi

Thanks for the report and apologies, this is now fixed.

**Comment by Buy-One** [comment]
Hi

Thanks for the report and apologies, this is now fixed.

If you feel like the issue has been solved feel free to close the ticket.
