### ISSUE TITLE
Accessibility: The two actions: "Move selected take FX down in the chain.lua" and "Move selected take FX up in the chain.lua" lose the system cursor

### ISSUE THREAD

**Issue by Lo-lo78** [Buy-One/REAPER-scripts#3]
@Buy-One 
Unfortunately I can't give you screen shots as I'm blind.
I can describe what happens step by step.
I move a plugin up and the screen reader tells me exactly where the plugin is in the FX chain.
Up to this point it's perfect!
Unfortunately, immediately afterwards when I move the arrows I find myself at the top of the FX chain and not where I moved the plugin previously.
The two sws actions:
"SWS/S&M: Move selected FX up in chain for selected tracks"
"SWS/S&M: Move selected FX down in chain for selected tracks"
These two actions do not lose focus.
If I move the plugins with SWS and then move the arrows I am exactly where I should be in the FX chain.
If you have time, try keyboard shortcuts.
I thank you so much!

**Comment by Buy-One** [comment]
Have you read the 'About' text inside the script?

I'll quote it here

>!!!! IMPORTANT !!!!
		
>If you choose to run the script with a shortcut, the shortcut scope
must be global (select appropriate option from the 'Scope' menu in 
the 'Keyboard/MIDI/OSC input' dialogue in the Action list). This will
ensure script operability when take under mouse cursor is targeted 
while its FX chain window is in focus.

**Comment by Lo-lo78** [comment]
@Buy-One 
Maybe my English is poor.
I meant a computer keyboard shortcut. It has nothing to do with midi.
I'm talking about the Reaper keymap.
I assigned shortcuts to your two actions and they work well.
I will read in the script if there is anything regarding the focus-.
You don't use the mouse if you are blind. It is used very little.
Could it be Cockos' problem that he loses focus?
Maybe if we can understand each other you will know what the problem is.
I don't think it's difficult to solve or understand.
Thank you!

**Comment by Buy-One** [comment]
In short, the scope of shortcuts must be global. MIDI is only mentioned in the name of shortcut assignment dialogue.

I came across this problem while writing the script and the solution is using shortcuts with global scope. How to enable it is described in the text i quoted above.

Are you using shortcuts with global scope?

**Comment by Buy-One** [comment]
@Lo-lo78

I couldn't replicate the problem using shortcut with or without global scope in REAPER 6.79 and in REAPER 7.02.

You say `Unfortunately, immediately afterwards when I move the arrows I find myself at the top of the FX chain`

Please clarify what `immediately afterwards` mean, immediately after what? What do you mean by `I find myself at the top of the FX chain`, does plugin selection change, at which point?

I will need very precise and detailed replication steps, like A, B, C etc. to be able to try to replicate the issue and hopefully solve it.

**Comment by Lo-lo78** [comment]
@Buy-One 
I'll try to explain myself.

When I am in the fx chain of the take and I move the last plugin the plugin is in the penultimate position of the chain.
It is OK!
As soon as I arrow down I select the first plugin at the top of the fx chain.

For example:

1.
"1 reaeq"
"2 reacomp"
"3 reaeq"; selected; move up
2.
The result is:
"1 reaeq"
"3 reaeq"
"2 reacomp"
3.
I press the down arrow key and find:
"1 reaeq" selected;
"3 reaeq"
"2 reacomp"
4.
If I moved the last effect actually the final result should be:
"1 reaeq"
"3 reaeq" selected;
"2 reacomp"

I hope that was clear.
Thank you!

**Comment by Buy-One** [comment]
In step 3 when you press the down arrow key, is this key mapped to the script which moves the FX down?

If it is, does the problem only affect the script which moves FX down?

**Comment by Lo-lo78** [comment]
The arrow keys work as in all Windows lists.
I haven't mapped it.
I mapped the two lua scripts to another part of the keyboarddel computer.
In a list, the up or down arrow keys simply select an item in a list.
It is by default.

**Comment by Lo-lo78** [comment]
Leave the arrow keys as default.
You should assign the two lua actions to two different keys.

**Comment by Buy-One** [comment]
I'm lost. 

1) In step 2 after you moved the FX up, which FX ends up being selected?

2) In step 3 do you try to move FX down with the script or do you simply press the down arrow key which is not mapped to anything?

**Comment by Lo-lo78** [comment]
@Buy-One 
Sorry!
You are right in step two the second is selected:
2.
The result is:
"1 reaeq"
"3 reaeq"; selected;
"2 reacomp"
3.
I press the down arrow key and find: (Not assigned to Reaper but is Windows default)
"1 reaeq" selected;
"3 reaeq"
"2 reacomp"

Simply after moving the FX from bottom to top to the second position the system cursor starts from the first from the top and not where I moved the plugin. It's as if you lost the selection of the plugin you just moved.

Thank you!

**Comment by Buy-One** [comment]
OK, I was able to replicate the problem and will try to solve it, although it's very likely that i'll have to rely on js_ReaScriptAPI extension.

**Comment by Lo-lo78** [comment]
@Buy-One 
These two scripts are already fully functional but it's great if you can fix them for a non-expert blind user.
I think he might be confused when moving plugins in the take's fx chain.

Surely you know the OSARA extension.
Just for information I leave you the contacts.
For these two scripts it is not needed but you might need it in the future if you have great ideas for new scripts.

git clone
https://github.com/jcsteh/osara

I have lots of your scripts from ReaTeam Scripts.
Compliments!
👍

**Comment by Buy-One** [comment]
Hi, i believe i've fixed both scripts. Please try the latest version. It doesn't require any additional extensions like i thought initially.

Yeah, at first i was submitting my scripts to ReaTeam repo, but after a few years the time it took to have my scripts merged with the master branch became frustrating, so i figured that managing my own repo would be more convenient.

**Comment by Lo-lo78** [comment]
@Buy-One 
Perfect!
It works very well.
Did you solve the problem!
Shall I close the issue? I think the issue is resolved.
👍
👏

**Comment by Buy-One** [comment]
I think i did. You can close the ticket, but feel free to re-open or open a new one if another issue emerges.
