### ISSUE TITLE
Is it possible to create a script " "BuyOne_Convert cycle action to Lua ReaScript.lua"

### ISSUE THREAD

**Issue by Lo-lo78** [Buy-One/REAPER-scripts#4]
Hi BuyOne!
It's a beautiful script:
"Script: BuyOne_Convert custom action to Lua ReaScript.lua"
Is it possible to also convert cycle actions?
I have the feeling you've already thought about it.
Can a lua script get to this level?
It would be very useful for portability of lua files.
It's interesting for sharing lua files on Reaper.
Thank you!

**Comment by Buy-One** [comment]
Yeah i did think about it but it requires much more thought than i've been willing to invest in it thus far.  So right now i don't have plans to create one.
