### ISSUE TITLE
action to select the two end points of a segment in an envelope

### ISSUE THREAD

**Issue by Javiramallo** [Buy-One/REAPER-scripts#5]
Hi Buy One.

Hope you are well!

About the script... mmm, it's hard to explain. 

Normally it works fine, but suddenly it starts to malfunction here and there and starts behaving strangely. The behavior of the bug is so random that it would be difficult to try to evolve to fix it. I think maybe I was wrong in thinking that this script would involve something much simpler, but I've already realized that getting it to work in all cases would be an incalculable amount of work.

So for me, we can leave it at that, if you don't mind.
As it is now it can help me in many cases and I am happy with that.

Thank you again for your effort and attention!

Hugs!

**Comment by Buy-One** [comment]
Hi

OK. But if you feel like there're some cases which should be addressed i'll be happy to look into them.

Cheers

**Comment by Buy-One** [comment]
Hi

OK. But if you feel like there're some cases which should be addressed i'll be happy to look into them.

Closing for now.

Cheers

**Comment by Javiramallo** [comment]
Right. If I detect some cases that could be predictible and reproducible,  I'll feel free yo border you again.

Really thanks!
