### ISSUE TITLE
Accessibility. Is it possible to create a lua script that tells the metronome DB?

### ISSUE THREAD

**Issue by Lo-lo78** [Buy-One/REAPER-scripts#6]
Hi Buyone, I don't know if it's possible but I would be interested in knowing the volume of the metronome in db.
To help you I can tell you that:
reaper.ShowConsoleMsg()
It's equal to:
reaper.osara_outputMessage()
I believe it is not necessary for a sighted person to have this lua script but for a blind person it can be very useful to know the volume of the metronome.
You might wonder why I'm asking you this.
There has been an issue on OSARA for years and they haven't bothered to close or resolve it.
Concretely, an action that tells the volume with reaper.osara_ouputMessage would be useful.
For example:
metronome 0.0 db. Metronome -1.5 db.
The message can also be modified. I haven't found anything to develop a lua that would tell me the volume of the metronome.
Thank you for everything you do!

Sorry for the English!

**Comment by Buy-One** [comment]
Hi,

Unfortunately there's no API to get metronome settings other than metronome pattern, so it's not possible.

**Comment by Lo-lo78** [comment]
@Buy-One 
OK thanks for the info. Maybe Cockos could solve the problem.
Thank you!
